// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGeiIIcAroC1996w6g3A9x1F1DdW9yyxM',
    appId: '1:407722243486:web:2f14f04ae40ed010a9928f',
    messagingSenderId: '407722243486',
    projectId: 'appxemay-c3961',
    authDomain: 'appxemay-c3961.firebaseapp.com',
    storageBucket: 'appxemay-c3961.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSUOC_SITnOSYstn-jqPICUlLGqjXsWR4',
    appId: '1:407722243486:android:b9e0cdc428a4aa55a9928f',
    messagingSenderId: '407722243486',
    projectId: 'appxemay-c3961',
    storageBucket: 'appxemay-c3961.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9cgj2OWlF25HrnrdqE3Fa-TiQc-y1RAg',
    appId: '1:407722243486:ios:f6d3e03e7734b7d1a9928f',
    messagingSenderId: '407722243486',
    projectId: 'appxemay-c3961',
    storageBucket: 'appxemay-c3961.appspot.com',
    iosBundleId: 'com.example.appXemay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9cgj2OWlF25HrnrdqE3Fa-TiQc-y1RAg',
    appId: '1:407722243486:ios:a07c5e40e17a4d68a9928f',
    messagingSenderId: '407722243486',
    projectId: 'appxemay-c3961',
    storageBucket: 'appxemay-c3961.appspot.com',
    iosBundleId: 'com.example.appXemay.RunnerTests',
  );
}
